import React, { useState } from 'react';
import { 
  Scale, 
  BarChart, 
  Activity, 
  CheckCircle2, 
  Download, 
  FileText, 
  ArrowRight,
  TrendingUp,
  Percent
} from 'lucide-react';
import { ObservationMarker, ViewMode } from '../types';
import { FLOAT_6902345_PROFILE, PROFILE_STATS } from '../data/oceanData';

interface ModelVsObsViewProps {
  observation: ObservationMarker;
  viewMode: ViewMode;
  onNavigateToProfiles: () => void;
}

export const ModelVsObsView: React.FC<ModelVsObsViewProps> = ({
  observation,
  viewMode,
  onNavigateToProfiles,
}) => {
  const [selectedDepth, setSelectedDepth] = useState<number>(500);
  const [displayMode, setDisplayMode] = useState<'bars' | 'scatter'>('bars');

  // Key depth levels for comparison
  const sampleDepths = [0, 100, 250, 500, 750, 1000, 1500, 2000];

  const currentPoint = FLOAT_6902345_PROFILE.find((p) => p.depth === selectedDepth) || FLOAT_6902345_PROFILE[9];

  // Bias calculations
  const tempBias = (currentPoint.modelTemp - currentPoint.observedTemp).toFixed(2);
  const tempBiasPct = (((currentPoint.modelTemp - currentPoint.observedTemp) / currentPoint.observedTemp) * 100).toFixed(1);
  const salinityBias = (currentPoint.modelSalinity - currentPoint.observedSalinity).toFixed(2);
  const salinityBiasPct = (((currentPoint.modelSalinity - currentPoint.observedSalinity) / currentPoint.observedSalinity) * 100).toFixed(2);

  const handleExportReport = () => {
    const reportText = `=====================================================
INCOIS BLUELENS OCEAN MODEL VALIDATION REPORT
Platform: ${observation.name} (${observation.wmoid})
Location: ${observation.latitude}°N, ${observation.longitude}°E
Timestamp: ${observation.dateTime}
=====================================================

Selected Validation Depth: ${selectedDepth} metres

TEMPERATURE (°C):
- Observed In-Situ: ${currentPoint.observedTemp} °C
- INCOIS ROMS Model: ${currentPoint.modelTemp} °C
- Model Bias: ${tempBias} °C (${tempBiasPct}%)
- Root Mean Square Error (RMSE): 0.28 °C
- Pearson Correlation (r): 0.992

SALINITY (PSU):
- Observed In-Situ: ${currentPoint.observedSalinity} PSU
- INCOIS ROMS Model: ${currentPoint.modelSalinity} PSU
- Model Bias: ${salinityBias} PSU (${salinityBiasPct}%)
- Root Mean Square Error (RMSE): 0.05 PSU
- Pearson Correlation (r): 0.985

VALIDATION GRADE: EXCELLENT / OPERATIONAL READY
Generated by BLUELENS v2.4 Platform (INCOIS)
`;
    const blob = new Blob([reportText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `INCOIS_Model_Validation_Report_${observation.id}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="w-full min-h-[calc(100vh-4rem)] bg-[#061220] p-4 sm:p-6 lg:p-8 select-none text-[#E6F4FF]">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between pb-4 border-b border-white/10 gap-3 mb-6">
        <div>
          <div className="flex items-center space-x-2.5">
            <Scale className="w-6 h-6 text-[#00C2FF]" />
            <h1 className="text-xl sm:text-2xl font-bold tracking-wide text-white glow-cyan">
              MODEL VS OBSERVATION COMPARISON
            </h1>
          </div>
          <p className="text-xs sm:text-sm text-[#00C2FF] font-medium mt-1">
            {viewMode === 'scientist'
              ? 'Real-Time Hydrodynamic Model Bias & Skill Score Evaluation (INCOIS ROMS vs Argo GDAC)'
              : 'How accurate is our ocean forecast compared to real robot sensors?'}
          </p>
        </div>

        {/* Action Controls */}
        <div className="flex items-center space-x-2">
          <div className="flex items-center space-x-1 bg-[#0B1D2E] p-1 rounded-xl border border-[#00C2FF]/30">
            <button
              onClick={() => setDisplayMode('bars')}
              className={`px-3 py-1.5 rounded-lg text-xs font-semibold transition-all ${
                displayMode === 'bars'
                  ? 'bg-[#00C2FF] text-[#061220] font-bold'
                  : 'text-white/70 hover:text-white'
              }`}
            >
              Grouped Bars
            </button>
            <button
              onClick={() => setDisplayMode('scatter')}
              className={`px-3 py-1.5 rounded-lg text-xs font-semibold transition-all ${
                displayMode === 'scatter'
                  ? 'bg-[#00C2FF] text-[#061220] font-bold'
                  : 'text-white/70 hover:text-white'
              }`}
            >
              1:1 Scatter Plot
            </button>
          </div>

          <button
            onClick={handleExportReport}
            className="flex items-center space-x-1.5 px-3 py-2 rounded-xl bg-[#0B1D2E] hover:bg-white/10 border border-white/15 text-xs font-semibold text-white transition-colors"
          >
            <FileText className="w-3.5 h-3.5 text-[#00C2FF]" />
            <span>Export Report</span>
          </button>
        </div>
      </div>

      {/* Explorer High-Level Accuracy Badge Banner (Screen 12 from PDF) */}
      <div className="mb-6 p-4 rounded-2xl bg-gradient-to-r from-[#0B1D2E] via-[#0B3D6B]/50 to-[#0B1D2E] border border-[#00C2FF]/30 flex flex-col sm:flex-row items-center justify-between gap-4 shadow-xl">
        <div className="flex items-center space-x-3 text-center sm:text-left">
          <div className="w-10 h-10 rounded-full bg-emerald-500/20 border border-emerald-400 flex items-center justify-center shrink-0">
            <CheckCircle2 className="w-6 h-6 text-emerald-300" />
          </div>
          <div>
            <div className="text-xs uppercase font-bold tracking-wider text-emerald-400">
              Forecast Reliability: High (Operational Grade)
            </div>
            <p className="text-xs text-white/80 mt-0.5">
              {viewMode === 'explorer'
                ? `Our ocean model predicted ${currentPoint.modelTemp}°C at ${selectedDepth}m; the Argo float measured ${currentPoint.observedTemp}°C. Excellent match!`
                : `Combined RMSE 0.28°C across 0–2000m column with Pearson correlation r = 0.992 against WMO GDAC.`}
            </p>
          </div>
        </div>

        {/* Depth Level Selector Pills */}
        <div className="flex items-center space-x-1 bg-[#061220] p-1 rounded-xl border border-white/10 overflow-x-auto">
          <span className="text-[10px] text-white/50 px-2 uppercase font-semibold">Depth:</span>
          {sampleDepths.map((d) => (
            <button
              key={d}
              onClick={() => setSelectedDepth(d)}
              className={`px-2.5 py-1 rounded-lg text-xs font-mono font-medium transition-all ${
                selectedDepth === d
                  ? 'bg-[#00C2FF] text-[#061220] font-bold'
                  : 'text-white/70 hover:text-white'
              }`}
            >
              {d === 0 ? 'Surface' : `${d}m`}
            </button>
          ))}
        </div>
      </div>

      {/* Main Comparison Layout */}
      {displayMode === 'bars' ? (
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 mb-6">
          {/* Temperature Comparison Card */}
          <div className="glass-panel p-5 rounded-2xl border border-[#FE5F4E]/30 shadow-2xl space-y-4">
            <div className="flex items-center justify-between border-b border-white/10 pb-3">
              <div className="flex items-center space-x-2">
                <span className="w-3 h-3 rounded-full bg-[#FE5F4E]" />
                <h3 className="text-base font-bold text-white">Temperature (°C) at {selectedDepth} m</h3>
              </div>
              <span className="text-xs font-mono px-2 py-0.5 rounded bg-[#061220] text-[#FE5F4E] border border-[#FE5F4E]/30 font-bold">
                Bias: {Number(tempBias) > 0 ? `+${tempBias}` : tempBias} °C ({Number(tempBiasPct) > 0 ? `+${tempBiasPct}` : tempBiasPct}%)
              </span>
            </div>

            {/* Visual Bar Comparison */}
            <div className="space-y-4 py-3">
              <div>
                <div className="flex justify-between text-xs mb-1.5">
                  <span className="text-[#FFB020] font-semibold">Observed Float Sensor:</span>
                  <span className="font-mono text-white font-bold">{currentPoint.observedTemp} °C</span>
                </div>
                <div className="w-full h-8 bg-[#061220] rounded-xl overflow-hidden p-1 border border-white/5">
                  <div
                    className="h-full bg-gradient-to-r from-[#FFB020] to-amber-300 rounded-lg transition-all duration-500 flex items-center justify-end pr-2 text-xs font-bold text-[#061220]"
                    style={{ width: `${(currentPoint.observedTemp / 32) * 100}%` }}
                  >
                    {currentPoint.observedTemp}°C
                  </div>
                </div>
              </div>

              <div>
                <div className="flex justify-between text-xs mb-1.5">
                  <span className="text-[#00C2FF] font-semibold">INCOIS ROMS Forecast Model:</span>
                  <span className="font-mono text-white font-bold">{currentPoint.modelTemp} °C</span>
                </div>
                <div className="w-full h-8 bg-[#061220] rounded-xl overflow-hidden p-1 border border-white/5">
                  <div
                    className="h-full bg-gradient-to-r from-[#00C2FF] to-cyan-300 rounded-lg transition-all duration-500 flex items-center justify-end pr-2 text-xs font-bold text-[#061220]"
                    style={{ width: `${(currentPoint.modelTemp / 32) * 100}%` }}
                  >
                    {currentPoint.modelTemp}°C
                  </div>
                </div>
              </div>
            </div>

            {/* Metrics */}
            <div className="grid grid-cols-3 gap-2 pt-3 border-t border-white/10 text-xs text-center font-mono">
              <div className="bg-[#061220]/60 p-2 rounded-lg">
                <span className="text-white/40 text-[10px] block">RMSE</span>
                <span className="text-white font-bold">0.28 °C</span>
              </div>
              <div className="bg-[#061220]/60 p-2 rounded-lg">
                <span className="text-white/40 text-[10px] block">CORRELATION</span>
                <span className="text-[#00C2FF] font-bold">r = 0.992</span>
              </div>
              <div className="bg-[#061220]/60 p-2 rounded-lg">
                <span className="text-white/40 text-[10px] block">CONFIDENCE</span>
                <span className="text-emerald-300 font-bold">98.4%</span>
              </div>
            </div>
          </div>

          {/* Salinity Comparison Card */}
          <div className="glass-panel p-5 rounded-2xl border border-[#00C2FF]/30 shadow-2xl space-y-4">
            <div className="flex items-center justify-between border-b border-white/10 pb-3">
              <div className="flex items-center space-x-2">
                <span className="w-3 h-3 rounded-full bg-[#00C2FF]" />
                <h3 className="text-base font-bold text-white">Salinity (PSU) at {selectedDepth} m</h3>
              </div>
              <span className="text-xs font-mono px-2 py-0.5 rounded bg-[#061220] text-[#00C2FF] border border-[#00C2FF]/30 font-bold">
                Bias: {Number(salinityBias) > 0 ? `+${salinityBias}` : salinityBias} PSU ({salinityBiasPct}%)
              </span>
            </div>

            {/* Visual Bar Comparison */}
            <div className="space-y-4 py-3">
              <div>
                <div className="flex justify-between text-xs mb-1.5">
                  <span className="text-[#FFB020] font-semibold">Observed Float Sensor:</span>
                  <span className="font-mono text-white font-bold">{currentPoint.observedSalinity} PSU</span>
                </div>
                <div className="w-full h-8 bg-[#061220] rounded-xl overflow-hidden p-1 border border-white/5">
                  <div
                    className="h-full bg-gradient-to-r from-[#FFB020] to-amber-300 rounded-lg transition-all duration-500 flex items-center justify-end pr-2 text-xs font-bold text-[#061220]"
                    style={{ width: `${((currentPoint.observedSalinity - 30) / 7) * 100}%` }}
                  >
                    {currentPoint.observedSalinity}
                  </div>
                </div>
              </div>

              <div>
                <div className="flex justify-between text-xs mb-1.5">
                  <span className="text-[#00C2FF] font-semibold">INCOIS ROMS Forecast Model:</span>
                  <span className="font-mono text-white font-bold">{currentPoint.modelSalinity} PSU</span>
                </div>
                <div className="w-full h-8 bg-[#061220] rounded-xl overflow-hidden p-1 border border-white/5">
                  <div
                    className="h-full bg-gradient-to-r from-[#00C2FF] to-cyan-300 rounded-lg transition-all duration-500 flex items-center justify-end pr-2 text-xs font-bold text-[#061220]"
                    style={{ width: `${((currentPoint.modelSalinity - 30) / 7) * 100}%` }}
                  >
                    {currentPoint.modelSalinity}
                  </div>
                </div>
              </div>
            </div>

            {/* Metrics */}
            <div className="grid grid-cols-3 gap-2 pt-3 border-t border-white/10 text-xs text-center font-mono">
              <div className="bg-[#061220]/60 p-2 rounded-lg">
                <span className="text-white/40 text-[10px] block">RMSE</span>
                <span className="text-white font-bold">0.05 PSU</span>
              </div>
              <div className="bg-[#061220]/60 p-2 rounded-lg">
                <span className="text-white/40 text-[10px] block">CORRELATION</span>
                <span className="text-[#00C2FF] font-bold">r = 0.985</span>
              </div>
              <div className="bg-[#061220]/60 p-2 rounded-lg">
                <span className="text-white/40 text-[10px] block">CONFIDENCE</span>
                <span className="text-emerald-300 font-bold">99.1%</span>
              </div>
            </div>
          </div>
        </div>
      ) : (
        /* 1:1 Scatter Plot Mode (Screen 12 from PDF) */
        <div className="glass-panel p-6 rounded-2xl border border-white/10 mb-6 flex flex-col items-center">
          <div className="text-sm font-bold text-white mb-2">
            1:1 Model vs Observed Scatter Plot (0–2000 m Water Column)
          </div>
          <p className="text-xs text-white/60 mb-4">
            Points falling on the diagonal dashed line represent perfect forecast accuracy.
          </p>
          <div className="w-full max-w-lg aspect-square relative bg-[#071629] rounded-xl border border-white/10 p-6 flex items-center justify-center">
            <svg viewBox="0 0 300 300" className="w-full h-full">
              {/* Grid */}
              <line x1="30" y1="270" x2="270" y2="270" stroke="rgba(255,255,255,0.2)" />
              <line x1="30" y1="30" x2="30" y2="270" stroke="rgba(255,255,255,0.2)" />
              {/* 1:1 Diagonal */}
              <line x1="30" y1="270" x2="270" y2="30" stroke="#00C2FF" strokeDasharray="4 4" strokeWidth="1.5" />
              {/* Plot points */}
              {FLOAT_6902345_PROFILE.map((pt) => {
                const cx = 30 + (pt.observedTemp / 32) * 240;
                const cy = 270 - (pt.modelTemp / 32) * 240;
                return (
                  <circle
                    key={pt.depth}
                    cx={cx}
                    cy={cy}
                    r="4.5"
                    fill="#FFB020"
                    stroke="#ffffff"
                    strokeWidth="1"
                  />
                );
              })}
              <text x="150" y="295" fill="white" fontSize="10" textAnchor="middle">
                Observed Temperature (°C)
              </text>
              <text transform="rotate(-90) translate(-150, 18)" fill="white" fontSize="10" textAnchor="middle">
                Model Temperature (°C)
              </text>
            </svg>
          </div>
        </div>
      )}

      {/* Observation Telemetry Provenance Banner */}
      <div className="p-4 rounded-xl bg-[#0B1D2E]/80 border border-white/5 flex flex-col sm:flex-row items-center justify-between text-xs gap-3">
        <div className="flex items-center space-x-3 text-white/70">
          <span>Platform: <strong className="text-white">{observation.name}</strong></span>
          <span>•</span>
          <span>WMO: <strong className="text-white">{observation.wmoid}</strong></span>
          <span>•</span>
          <span>Timestamp: <strong className="text-white">{observation.dateTime}</strong></span>
        </div>
        <button
          onClick={onNavigateToProfiles}
          className="text-[#00C2FF] font-semibold hover:underline flex items-center"
        >
          <span>Return to Full Depth Profiles</span>
          <ArrowRight className="w-3.5 h-3.5 ml-1" />
        </button>
      </div>
    </div>
  );
};
